///
///  Platform_SDL.cpp
///

#include "stdafx.h"
#include "Platform.h"
#include "Globals.h"
#include "tutorial.h"
#include "SDLU.h"
#include "SDL.h"



Platform_Keycode playerKeys[2][4] =
{
    { SDLK_a, SDLK_d, SDLK_x, SDLK_s },
    { SDLK_LEFT, SDLK_RIGHT, SDLK_DOWN, SDLK_UP }
};

const Platform_Keycode defaultPlayerKeys[2][4] =
{
    { SDLK_a, SDLK_d, SDLK_x, SDLK_s },
    { SDLK_LEFT, SDLK_RIGHT, SDLK_DOWN, SDLK_UP }
};


void Platform_ReportAchievement(const char* /*achievementName*/, float /*percentComplete*/) {}
#ifndef __EMSCRIPTEN__
void Platform_Init() {}
void Platform_NotifyScreenLeftEdge(int /*leftEdge*/) {}
void Platform_SetPauseButtonPosition(MPoint /*pt*/) {}
void Platform_SetPauseButtonVisible(bool /*visible*/) {}
void Platform_CompositeOverlays() {}
void Platform_PromptForHighScoreName(char* /*name*/, int /*maxLen*/, const char* /*message*/) {}
bool Platform_IsTouchDevice() { return false; }
bool Platform_IsPauseButtonTap(MPoint /*canvasPt*/) { return false; }
#endif

void Platform_Error( const char* extra )
{
#ifdef __EMSCRIPTEN__
    fprintf(stderr, "Candy Crisis fatal error: %s\n", extra);
#else
    char error[1024];
    snprintf(error, sizeof(error), "Sorry, a critical error has occurred. Please report the following error message:\n    %s", extra );
    SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_ERROR, "Candy Crisis", error, NULL);
#endif
    abort();
}

uint32_t Platform_GetTicks()
{
    return SDL_GetTicks();
}


const char* Platform_GetKeyName(Platform_Keycode k)
{
    return SDL_GetKeyName(k);
}


void Platform_FadeIn()
{
    if (!g_frontTexture) return;

    Uint32 start = SDL_GetTicks();
    Uint32 now = start;
    const Uint32 duration = 500;

    while (now - start < duration)
    {
        float t = (float)(now - start) / (float)duration;
        Uint8 val = (Uint8)(255 * t);

        SDL_SetTextureColorMod(g_frontTexture, val, val, val);
        
        SDL_SetRenderTarget(g_renderer, NULL);
        SDL_SetRenderDrawColor(g_renderer, 0, 0, 0, 255);
        SDL_RenderClear(g_renderer);
        SDL_RenderCopy(g_renderer, g_frontTexture, NULL, NULL);
        SDL_RenderPresent(g_renderer);
        
        SDLU_Yield();
        now = SDL_GetTicks();
    }
    
    SDL_SetTextureColorMod(g_frontTexture, 255, 255, 255);
    SDL_SetRenderTarget(g_renderer, NULL);
    SDL_RenderClear(g_renderer);
    SDL_RenderCopy(g_renderer, g_frontTexture, NULL, NULL);
    SDL_RenderPresent(g_renderer);
    
    SDL_SetRenderTarget(g_renderer, g_frontTexture);
}


void Platform_FadeOut()
{
    if (!g_frontTexture) return;

    Uint32 start = SDL_GetTicks();
    Uint32 now = start;
    const Uint32 duration = 500;

    while (now - start < duration)
    {
        float t = (float)(now - start) / (float)duration;
        Uint8 val = (Uint8)(255 * (1.0f - t));

        SDL_SetTextureColorMod(g_frontTexture, val, val, val);
        
        SDL_SetRenderTarget(g_renderer, NULL);
        SDL_SetRenderDrawColor(g_renderer, 0, 0, 0, 255);
        SDL_RenderClear(g_renderer);
        SDL_RenderCopy(g_renderer, g_frontTexture, NULL, NULL);
        SDL_RenderPresent(g_renderer);
        
        SDLU_Yield();
        now = SDL_GetTicks();
    }
    
    SDL_SetTextureColorMod(g_frontTexture, 255, 255, 255);
    
    SDL_SetRenderTarget(g_renderer, NULL);
    SDL_SetRenderDrawColor(g_renderer, 0, 0, 0, 255);
    SDL_RenderClear(g_renderer);
    SDL_RenderPresent(g_renderer);

    SDL_SetRenderTarget(g_renderer, g_frontTexture);
    SDL_SetRenderDrawColor(g_renderer, 0, 0, 0, 255);
    SDL_RenderClear(g_renderer);
}

AutoPattern touchTutorialPattern[] =
{
    { e_AutoCommand_Message,        0,   0,   "Welcome to\nyour first day\nof Candy School!" },
    { e_AutoCommand_Wait,      60,  0,   NULL },
    { e_AutoCommand_Retrieve,       1,   1,   NULL },
    { e_AutoCommand_Wait,      60,  0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "I'm Miss Gumdrop.\nLet's get started!" },
    { e_AutoCommand_Wait,      140, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "Candies like these\nhave started\nappearing every-\nwhere throughout\nour village." },
    { e_AutoCommand_Wait,      200, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "They always\ncome in pairs!" },
    { e_AutoCommand_Wait,      100, 0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       2,   2,   NULL },
    { e_AutoCommand_Message,        0,   0,   "Be careful! You\ncan't let them\noverflow the\nscreen." },
    { e_AutoCommand_Wait,      150, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "Fortunately, you\ncan control them!" },
    { e_AutoCommand_Wait,       70, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropDevice" },
    { e_AutoCommand_Wait,       90, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandCenter" },
    { e_AutoCommand_Wait,        4, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandLeft1" },
    { e_AutoCommand_Wait,        4, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandLeft2" },
    { e_AutoCommand_Position,       0,   0,   NULL },
    { e_AutoCommand_Wait,        20, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandCenter" },
    { e_AutoCommand_Wait,        4, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandDown1" },
    { e_AutoCommand_Wait,        4, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandDown2" },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropDevice" },
    { e_AutoCommand_Message,        0,   0,   "Swipe left or\nright to position\nthe candies." },
    { e_AutoCommand_Retrieve,       3,   3,   NULL },
    { e_AutoCommand_Wait,       90, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandCenter" },
    { e_AutoCommand_Wait,        4, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandRight1" },
    { e_AutoCommand_Wait,        4, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandRight2" },
    { e_AutoCommand_Position,       5,   0,   NULL },
    { e_AutoCommand_Wait,        20, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandCenter" },
    { e_AutoCommand_Wait,        4, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandDown1" },
    { e_AutoCommand_Wait,        4, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandDown2" },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropDevice" },
    { e_AutoCommand_Message,        0,   0,   "The candies can\nalso rotate around\neach other." },
    { e_AutoCommand_Retrieve,       4,   3,   NULL },
    { e_AutoCommand_Wait,       60, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandCenter" },
    { e_AutoCommand_Wait,        4, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandClick1" },
    { e_AutoCommand_Wait,        4, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandClick2" },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,        4, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandCenter" },
    { e_AutoCommand_Wait,       20, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandClick1" },
    { e_AutoCommand_Wait,        3, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandClick2" },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,        5, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "Tap to make them\nspin!" },
    { e_AutoCommand_Wait,       20, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandCenter" },
    { e_AutoCommand_Wait,        3, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandClick1" },
    { e_AutoCommand_Wait,        3, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandClick2" },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,        3, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandCenter" },
    { e_AutoCommand_Wait,        3, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandClick1" },
    { e_AutoCommand_Wait,        3, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandClick2" },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,        8, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandCenter" },
    { e_AutoCommand_Wait,        3, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandClick1" },
    { e_AutoCommand_Wait,        3, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandClick2" },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,        8,  0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandCenter" },
    { e_AutoCommand_Wait,        3, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandClick1" },
    { e_AutoCommand_Wait,        3, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandClick2" },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,        3, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandCenter" },
    { e_AutoCommand_Wait,        8,  0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandRight1" },
    { e_AutoCommand_Wait,        3, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandRight2" },
    { e_AutoCommand_Position,       5,   0,   NULL },
    { e_AutoCommand_Wait,        8, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandCenter" },
    { e_AutoCommand_Message,        0,   0,   "And swiping down\nmakes the candy\ndrop down." },
    { e_AutoCommand_Wait,       15, 0,   NULL },
    { e_AutoCommand_Wait,        4, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandDown1" },
    { e_AutoCommand_Wait,        4, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandDown2" },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Wait,       40, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropHandCenter" },
    { e_AutoCommand_Wait,       40, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/Web/BackdropDevice" },
    { e_AutoCommand_Message,        0,   0,   "To pause the game\nor quit, tap the\npause button." },
    { e_AutoCommand_Wait,       10, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/BackdropBlank" },
    { e_AutoCommand_Wait,      190, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "These candies are\nhighly reactive\nto color!" },
    { e_AutoCommand_Retrieve,       2,   2,   NULL },
    { e_AutoCommand_Wait,      200, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "So when four\npieces of the\nsame color come\ninto contact..." },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/BackdropCandies" },
    { e_AutoCommand_Position,       1,   0,   NULL },
    { e_AutoCommand_Wait,      180, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "... they pop!" },
    { e_AutoCommand_Wait,      15,  0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/BackdropCandyPop" },
    { e_AutoCommand_Wait,      15,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/BackdropBlank" },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "Let's see that\nonce again." },
    { e_AutoCommand_Retrieve,       1,   1,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/BackdropCandies" },
    { e_AutoCommand_Wait,      120, 0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/BackdropCandyPop" },
    { e_AutoCommand_Message,        0,   0,   "Pop!" },
    { e_AutoCommand_Wait,      15,  0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/BackdropBlank" },
    { e_AutoCommand_Wait,      50, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "You can even get\nfive or more\npieces to pop\nall at the same\ntime!" },
    { e_AutoCommand_Retrieve,       4,   4,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Position,       4,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       4,   4,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Position,       3,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       4,   4,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Position,       4,   0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "Pop!\nTechniques like\nthis can earn\nlots of bonus\npoints." },
    { e_AutoCommand_Wait,      180, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "You can also pop\nmore than one\ncolor at once." },
    { e_AutoCommand_Retrieve,       5,   5,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Position,       4,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       6,   5,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Position,       3,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       3,   5,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      10,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      10,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Position,       5,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "All right!" },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       0,   6,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "You can even set\nup devastating\nchain reactions..." },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       0,   6,   NULL },
    { e_AutoCommand_Wait,      90,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       6,   6,   NULL },
    { e_AutoCommand_Wait,      60,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       0,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Position,       1,   0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "... like this!" },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "Tricky, isn't it?" },
    { e_AutoCommand_Retrieve,       1,   2,   NULL },
    { e_AutoCommand_Wait,      60,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       1,   2,   NULL },
    { e_AutoCommand_Wait,      60,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       3,   1,   NULL },
    { e_AutoCommand_Wait,      60,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       3,   2,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Position,       3,   0,   NULL },
    { e_AutoCommand_Message,        0,   0,  "Let's see one\nmore example of\na chain\nreaction." },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       1,   2,   NULL },
    { e_AutoCommand_Wait,      60,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       5,   5,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Position,       1,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       5,   3,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      10,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      10,  0,   NULL },
    { e_AutoCommand_Position,       1,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       3,   5,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Position,       0,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      10,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       3,   3,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Position,       0,   0,   NULL },
    { e_AutoCommand_Wait,      20,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Wait,      90,  0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "There's one more\nthing you need to\nknow about..." },
    { e_AutoCommand_Wait,      180, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "Watch out for\nthe see-through\ncandy!" },
    { e_AutoCommand_Wait,      60,  0,   NULL },
    { e_AutoCommand_Punish,         18,  0,   NULL },
    { e_AutoCommand_Retrieve,       1,   1,   NULL },
    { e_AutoCommand_Wait,      120, 0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Position,       0,   0,   NULL },
    { e_AutoCommand_Wait,      20,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "When your\nopponent pops\na group of\ncandies..." },
    { e_AutoCommand_Retrieve,       1,   1,   NULL },
    { e_AutoCommand_Wait,      90,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Position,       4,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       1,   1,   NULL },
    { e_AutoCommand_Message,        0,   0,   "They also send\nsome transparent\npieces to you!" },
    { e_AutoCommand_Wait,      60,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      110, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "You can get rid of\nthese pieces by\npopping something\nnext to them." },
    { e_AutoCommand_Wait,      150, 0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Wait,      60,  0,   NULL },
    { e_AutoCommand_Retrieve,       1,   2,   NULL },
    { e_AutoCommand_Message,        0,   0,   "There are also\nsome bonus items\nwhich can come\nin handy." },
    { e_AutoCommand_Wait,      20,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Position,       0,   0,   NULL },
    { e_AutoCommand_Wait,      20,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       3,   1,   NULL },
    { e_AutoCommand_Wait,      20,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      10,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      10,  0,   NULL },
    { e_AutoCommand_Position,       0,   0,   NULL },
    { e_AutoCommand_Wait,      20,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       1,   3,   NULL },
    { e_AutoCommand_Wait,      10,  0,   NULL },
    { e_AutoCommand_Position,       1,   0,   NULL },
    { e_AutoCommand_Wait,      15,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "One of these\nbonus items is\nthe Crazy Candy!" },
    { e_AutoCommand_Retrieve,       -1,  2,   NULL },
    { e_AutoCommand_Wait,      15,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      10,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      100, 0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "The Crazy Candy\ntakes on the\ncolor of one of\nits neighbors." },
    { e_AutoCommand_Wait,      60,  0,   NULL },
    { e_AutoCommand_Retrieve,       3,   4,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Position,       4,   0,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       1,   5,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Position,       1,   0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "Another useful\nbonus item is\nthe bomb!" },
    { e_AutoCommand_Retrieve,       2,   3,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Position,       0,   0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       0,   3,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       3,   2,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Position,       5,   0,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       4,   3,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Position,       3,   0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       2,   3,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Position,       5,   0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve, kBombBottom, kBombTop, NULL },
    { e_AutoCommand_Message,        0,   0,   "When the bomb\nlands on one\ncolor of candy, all\npieces of that\ncolor will pop!" },
    { e_AutoCommand_Wait,      100, 0,   NULL },
    { e_AutoCommand_Position,       4,   0,   NULL },
    { e_AutoCommand_Wait,      120, 0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Wait,      200, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "Now you're ready\nto play Candy\nCrisis.\nGood luck!" },
    { e_AutoCommand_Wait,      270, 0,   NULL },
    { e_AutoCommand_ShowStartMenu,       0,   0,   NULL }
};

AutoPattern tutorialPattern[] =
{
    { e_AutoCommand_Message,        0,   0,   "Welcome to\nyour first day\nof Candy School!" },
    { e_AutoCommand_Wait,      60,  0,   NULL },
    { e_AutoCommand_Retrieve,       1,   1,   NULL },
    { e_AutoCommand_Wait,      60,  0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "I'm Miss Gumdrop.\nLet's get started!" },
    { e_AutoCommand_Wait,      140, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "Candies like these\nhave started\nappearing every-\nwhere throughout\nour village." },
    { e_AutoCommand_Wait,      200, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "They always\ncome in pairs!" },
    { e_AutoCommand_Wait,      100, 0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       2,   2,   NULL },
    { e_AutoCommand_Message,        0,   0,   "Be careful! You\ncan't let them\noverflow the\nscreen." },
    { e_AutoCommand_Wait,      150, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "Fortunately, they\ncan be controlled\nwith your keyboard!" },
    { e_AutoCommand_Wait,      170, 0,   NULL },
    { e_AutoCommand_Position,       0,   0,   NULL },
    { e_AutoCommand_Wait,       30, 0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "Press '~~' to\nmake the pieces\nmove left, and\n'||' will move\nthem right." },
    { e_AutoCommand_Retrieve,       3,   3,   NULL },
    { e_AutoCommand_Wait,      100, 0,   NULL },
    { e_AutoCommand_Position,       5,   0,   NULL },
    { e_AutoCommand_Wait,       30, 0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "The candies can\nalso rotate around\neach other." },
    { e_AutoCommand_Retrieve,       4,   3,   NULL },
    { e_AutoCommand_Wait,       70, 0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,       27, 0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,        5, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "Press '{{'\nto make them\nspin!" },
    { e_AutoCommand_Wait,       26, 0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,        9, 0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,        14, 0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,        14,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,        14, 0,   NULL },
    { e_AutoCommand_Position,       5,   0,   NULL },
    { e_AutoCommand_Wait,        8, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "And pressing\n'``' makes the\ncandy drop down." },
    { e_AutoCommand_Wait,       23, 0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Wait,       80, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "To pause the game\nor quit to the main\nmenu, press 'Esc.'" },
    { e_AutoCommand_Wait,       10, 0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/BackdropBlank" },
    { e_AutoCommand_Wait,      190, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "These candies are\nhighly reactive\nto color!" },
    { e_AutoCommand_Retrieve,       2,   2,   NULL },
    { e_AutoCommand_Wait,      200, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "So when four\npieces of the\nsame color come\ninto contact..." },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/BackdropCandies" },
    { e_AutoCommand_Position,       1,   0,   NULL },
    { e_AutoCommand_Wait,      180, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "... they pop!" },
    { e_AutoCommand_Wait,      15,  0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/BackdropCandyPop" },
    { e_AutoCommand_Wait,      15,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/BackdropBlank" },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "Let's see that\nonce again." },
    { e_AutoCommand_Retrieve,       1,   1,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/BackdropCandies" },
    { e_AutoCommand_Wait,      120, 0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/BackdropCandyPop" },
    { e_AutoCommand_Message,        0,   0,   "Pop!" },
    { e_AutoCommand_Wait,      15,  0,   NULL },
    { e_AutoCommand_UpdateBackdrop, 0,   0,   "/BackdropBlank" },
    { e_AutoCommand_Wait,      50, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "You can even get\nfive or more\npieces to pop\nall at the same\ntime!" },
    { e_AutoCommand_Retrieve,       4,   4,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Position,       4,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       4,   4,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Position,       3,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       4,   4,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Position,       4,   0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "Pop!\nTechniques like\nthis can earn\nlots of bonus\npoints." },
    { e_AutoCommand_Wait,      180, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "You can also pop\nmore than one\ncolor at once." },
    { e_AutoCommand_Retrieve,       5,   5,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Position,       4,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       6,   5,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Position,       3,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       3,   5,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      10,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      10,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Position,       5,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "All right!" },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       0,   6,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "You can even set\nup devastating\nchain reactions..." },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       0,   6,   NULL },
    { e_AutoCommand_Wait,      90,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       6,   6,   NULL },
    { e_AutoCommand_Wait,      60,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       0,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Position,       1,   0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "... like this!" },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "Tricky, isn't it?" },
    { e_AutoCommand_Retrieve,       1,   2,   NULL },
    { e_AutoCommand_Wait,      60,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       1,   2,   NULL },
    { e_AutoCommand_Wait,      60,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       3,   1,   NULL },
    { e_AutoCommand_Wait,      60,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       3,   2,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Position,       3,   0,   NULL },
    { e_AutoCommand_Message,        0,   0,  "Let's see one\nmore example of\na chain\nreaction." },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       1,   2,   NULL },
    { e_AutoCommand_Wait,      60,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       5,   5,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Position,       1,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       5,   3,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      10,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      10,  0,   NULL },
    { e_AutoCommand_Position,       1,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       3,   5,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Position,       0,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      10,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       3,   3,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_Position,       0,   0,   NULL },
    { e_AutoCommand_Wait,      20,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Wait,      90,  0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "There's one more\nthing you need to\nknow about..." },
    { e_AutoCommand_Wait,      180, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "Watch out for\nthe see-through\ncandy!" },
    { e_AutoCommand_Wait,      60,  0,   NULL },
    { e_AutoCommand_Punish,         18,  0,   NULL },
    { e_AutoCommand_Retrieve,       1,   1,   NULL },
    { e_AutoCommand_Wait,      120, 0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Position,       0,   0,   NULL },
    { e_AutoCommand_Wait,      20,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "When your\nopponent pops\na group of\ncandies..." },
    { e_AutoCommand_Retrieve,       1,   1,   NULL },
    { e_AutoCommand_Wait,      90,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Position,       4,   0,   NULL },
    { e_AutoCommand_Wait,      30,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       1,   1,   NULL },
    { e_AutoCommand_Message,        0,   0,   "They also send\nsome transparent\npieces to you!" },
    { e_AutoCommand_Wait,      60,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      110, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "You can get rid of\nthese pieces by\npopping something\nnext to them." },
    { e_AutoCommand_Wait,      150, 0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Wait,      60,  0,   NULL },
    { e_AutoCommand_Retrieve,       1,   2,   NULL },
    { e_AutoCommand_Message,        0,   0,   "There are also\nsome bonus items\nwhich can come\nin handy." },
    { e_AutoCommand_Wait,      20,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Position,       0,   0,   NULL },
    { e_AutoCommand_Wait,      20,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       3,   1,   NULL },
    { e_AutoCommand_Wait,      20,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      10,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      10,  0,   NULL },
    { e_AutoCommand_Position,       0,   0,   NULL },
    { e_AutoCommand_Wait,      20,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       1,   3,   NULL },
    { e_AutoCommand_Wait,      10,  0,   NULL },
    { e_AutoCommand_Position,       1,   0,   NULL },
    { e_AutoCommand_Wait,      15,  0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "One of these\nbonus items is\nthe Crazy Candy!" },
    { e_AutoCommand_Retrieve,       -1,  2,   NULL },
    { e_AutoCommand_Wait,      15,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      10,  0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      100, 0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "The Crazy Candy\ntakes on the\ncolor of one of\nits neighbors." },
    { e_AutoCommand_Wait,      60,  0,   NULL },
    { e_AutoCommand_Retrieve,       3,   4,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Position,       4,   0,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       1,   5,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Position,       1,   0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "Another useful\nbonus item is\nthe bomb!" },
    { e_AutoCommand_Retrieve,       2,   3,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Position,       0,   0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       0,   3,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       3,   2,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Position,       5,   0,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       4,   3,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Position,       3,   0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Retrieve,       2,   3,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Spin,           0,   0,   NULL },
    { e_AutoCommand_Wait,      5,   0,   NULL },
    { e_AutoCommand_Position,       5,   0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },	
    { e_AutoCommand_Retrieve, kBombBottom, kBombTop, NULL },
    { e_AutoCommand_Message,        0,   0,   "When the bomb\nlands on one\ncolor of candy, all\npieces of that\ncolor will pop!" },
    { e_AutoCommand_Wait,      100, 0,   NULL },
    { e_AutoCommand_Position,       4,   0,   NULL },
    { e_AutoCommand_Wait,      120, 0,   NULL },
    { e_AutoCommand_kBlockUntilDrop, 0,   0,   NULL },
    { e_AutoCommand_Wait,      200, 0,   NULL },
    { e_AutoCommand_Message,        0,   0,   "Now you're ready\nto play Candy\nCrisis.\nGood luck!" },
    { e_AutoCommand_Wait,      270, 0,   NULL },
    { e_AutoCommand_ShowStartMenu,       0,   0,   NULL }
};

/*
AutoPattern tutorialPattern[] =
{
    { kMessage,        0,   0,   "Welcome to the\nCandy Crisis\ntutorial!" },
    { kIdleTicks,      180, 0,   NULL },
    { kMessage,        0,   0,   "I'll be your guide\nthroughout the\ntutorial. Let's\nget started!" },
    { kRetrieve,       1,   1,   NULL },
    { kIdleTicks,      240, 0,   NULL },
    { kMessage,        0,   0,   "When you start the\ngame, you'll find a\npair of candies\nfalling from the sky." },
    { kIdleTicks,      240, 0,   NULL },
    { kMessage,        0,   0,   "Your goal is to\nkeep these candies\nfrom overflowing the\nboard!" },
    { kBlockUntilLand, 0,   0,   NULL },
    { kRetrieve,       2,   2,   NULL },
    { kIdleTicks,      60,  0,   NULL },
    { kMessage,        0,   0,   "You control the\ncandy by moving\nthem left and right." },
    { kIdleTicks,      120, 0,   NULL },
    { kPosition,       0,   0,   NULL },
    { kIdleTicks,      120, 0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kMessage,        0,   0,   "Press '~~'\nto make the pieces\nmove left." },
    { kRetrieve,       3,   3,   NULL },
    { kIdleTicks,      60,  0,   NULL },
    { kPosition,       5,   0,   NULL },
    { kIdleTicks,      90,  0,   NULL },
    { kMessage,        0,   0,  "Use '||' to\nmake the pieces\nmove right." },
    { kIdleTicks,      180, 0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kMessage,        0,   0,   "You can also\nmake the pieces\nrotate around each\nother." },
    { kRetrieve,       4,   3,   NULL },
    { kIdleTicks,      180, 0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kMessage,        0,   0,   "Press '{{'\nto make the pieces\nrotate." },
    { kIdleTicks,      30,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kPosition,       5,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kMessage,        0,   0,   "Also, '``'\ncauses the candy\nto drop faster." },
    { kIdleTicks,      180, 0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kMessage,        0,   0,   "To pause the game\nor adjust settings,\npress 'esc.'" },
    { kIdleTicks,      280, 0,   NULL },
    { kMessage,        0,   0,   "The candy in\nthis game is made\nfrom a highly\nunstable substance!" },
    { kRetrieve,       2,   2,   NULL },
    { kIdleTicks,      200, 0,   NULL },
    { kMessage,        0,   0,   "So when four\npieces of the same\ncolor come into\ncontact..." },
    { kPosition,       1,   0,   NULL },
    { kIdleTicks,      180, 0,   NULL },
    { kMessage,        0,   0,   "... they vaporize!" },
    { kIdleTicks,      30,  0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kIdleTicks,      60,  0,   NULL },
    { kMessage,        0,   0,   "Let's see that\nonce again." },
    { kRetrieve,       1,   1,   NULL },
    { kIdleTicks,      120, 0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kMessage,        0,   0,   "Pop!" },
    { kIdleTicks,      120, 0,   NULL },
    { kMessage,        0,   0,   "You can even get\nfive or more\npieces to pop\nall at the same\ntime!" },
    { kRetrieve,       4,   4,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kPosition,       4,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       4,   4,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kPosition,       3,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       4,   4,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kPosition,       4,   0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kMessage,        0,   0,   "Pop!\n\nTechniques like this\ncan earn lots of\nbonus points." },
    { kIdleTicks,      180, 0,   NULL },
    { kMessage,        0,   0,   "You can also pop\nmore than one color\nat once." },
    { kRetrieve,       5,   5,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kPosition,       4,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       6,   5,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kPosition,       3,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       3,   5,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      10,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      10,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kPosition,       5,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kMessage,        0,   0,   "All right!" },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       0,   6,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kMessage,        0,   0,   "You can even set\nup devastating\nchain reactions..." },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       0,   6,   NULL },
    { kIdleTicks,      90,  0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       6,   6,   NULL },
    { kIdleTicks,      60,  0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       0,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kPosition,       1,   0,   NULL },
    { kMessage,        0,   0,   "... like this!" },
    { kIdleTicks,      30,  0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kMessage,        0,   0,   "Tricky, isn't it?" },
    { kRetrieve,       1,   2,   NULL },
    { kIdleTicks,      60,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       1,   2,   NULL },
    { kIdleTicks,      60,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       3,   1,   NULL },
    { kIdleTicks,      60,  0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       3,   2,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kPosition,       3,   0,   NULL },
    { kMessage,        0,   0,  "Let's see one more\nexample of a chain\nreaction." },
    { kIdleTicks,      30,  0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       1,   2,   NULL },
    { kIdleTicks,      60,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       5,   5,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kPosition,       1,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       5,   3,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      10,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      10,  0,   NULL },
    { kPosition,       1,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       3,   5,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kPosition,       0,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      10,  0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       3,   3,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kPosition,       0,   0,   NULL },
    { kIdleTicks,      20,  0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kIdleTicks,      90,  0,   NULL },
    { kMessage,        0,   0,   "There's one more\nthing you need to\nknow about..." },
    { kIdleTicks,      180, 0,   NULL },
    { kMessage,        0,   0,   "Watch out for the\nsee-through candy!" },
    { kIdleTicks,      60,  0,   NULL },
    { kPunish,         18,  0,   NULL },
    { kRetrieve,       1,   1,   NULL },
    { kIdleTicks,      120, 0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kPosition,       0,   0,   NULL },
    { kIdleTicks,      20,  0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kMessage,        0,   0,   "When your opponent\nvaporizes a group of\ncandies, they also\nsend some transparent\npieces to you!" },
    { kRetrieve,       1,   1,   NULL },
    { kIdleTicks,      90,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kPosition,       4,   0,   NULL },
    { kIdleTicks,      30,  0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       1,   1,   NULL },
    { kIdleTicks,      60,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      90,  0,   NULL },
    { kMessage,        0,   0,   "You can get rid of\nthese pieces by\nvaporizing something\nnext to them." },
    { kIdleTicks,      150, 0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kIdleTicks,      60,  0,   NULL },
    { kRetrieve,       1,   2,   NULL },
    { kMessage,        0,   0,   "There are also\nsome bonus items\nwhich can come\nin handy." },
    { kIdleTicks,      20,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kPosition,       0,   0,   NULL },
    { kIdleTicks,      20,  0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       3,   1,   NULL },
    { kIdleTicks,      20,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      10,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      10,  0,   NULL },
    { kPosition,       0,   0,   NULL },
    { kIdleTicks,      20,  0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       1,   3,   NULL },
    { kIdleTicks,      10,  0,   NULL },
    { kPosition,       1,   0,   NULL },
    { kIdleTicks,      15,  0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kMessage,        0,   0,   "One of these bonus\nitems is the Crazy\nCandy!" },
    { kRetrieve,       -1,  2,   NULL },
    { kIdleTicks,      15,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      10,  0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      100, 0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kMessage,        0,   0,   "The Crazy Candy\ntakes on the\ncolor of one of\nits neighbors." },
    { kIdleTicks,      60,  0,   NULL },
    { kRetrieve,       3,   4,   NULL },
    { kIdleTicks,      5,   0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kPosition,       4,   0,   NULL },
    { kIdleTicks,      5,   0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       1,   5,   NULL },
    { kIdleTicks,      5,   0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      5,   0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      5,   0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      5,   0,   NULL },
    { kPosition,       1,   0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kMessage,        0,   0,   "Another useful bonus\nitem is the bomb!" },
    { kRetrieve,       2,   3,   NULL },
    { kIdleTicks,      5,   0,   NULL },
    { kPosition,       0,   0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       0,   3,   NULL },
    { kIdleTicks,      5,   0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       3,   2,   NULL },
    { kIdleTicks,      5,   0,   NULL },
    { kPosition,       5,   0,   NULL },
    { kIdleTicks,      5,   0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       4,   3,   NULL },
    { kIdleTicks,      5,   0,   NULL },
    { kPosition,       3,   0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kRetrieve,       2,   3,   NULL },
    { kIdleTicks,      5,   0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      5,   0,   NULL },
    { kSpin,           0,   0,   NULL },
    { kIdleTicks,      5,   0,   NULL },
    { kPosition,       5,   0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },	
    { kRetrieve, kBombBottom, kBombTop, NULL },
    { kMessage,        0,   0,   "When the bomb lands\non one color\nof candy, all\npieces of that\ncolor will\nvaporize!" },
    { kIdleTicks,      100, 0,   NULL },
    { kPosition,       4,   0,   NULL },
    { kIdleTicks,      120, 0,   NULL },
    { kBlockUntilDrop, 0,   0,   NULL },
    { kIdleTicks,      200, 0,   NULL },
    { kMessage,        0,   0,   "Now you're ready\nto play Candy Crisis.\nGood luck!" },
    { kIdleTicks,      270, 0,   NULL },
    
    { e_AutoCommand_ShowStartMenu, 0,   0,   NULL }
};
*/
